### ISSUE TITLE
python3.9 causes assertion error

### ISSUE THREAD

**Issue by paulhfischer** [asottile/add-trailing-comma#106]
ran into the following issue using the add-trailing-comma hook on macOS with python3.9 (works fine with `<= 3.8`). `.pre-commit-config.yaml` is the one from [pre-commit](https://github.com/pre-commit/pre-commit/blob/master/.pre-commit-config.yaml).

i tried reinstalling python3.9 and cleaning the pre-commit cache but nothing changed.

error and system info:

```console
+ sw_vers
ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69
```

```console
+ python --version
Python 3.9.1
```

```console
+ pre-commit --version
pre-commit 2.9.3
```

```console
+ pre-commit run add-trailing-comma --all-files
Add trailing commas......................................................Failed
- hook id: add-trailing-comma
- exit code: 1

Traceback (most recent call last):
  File "/Users/paulhfischer/.cache/pre-commit/repothj9r_n4/py_env-python3.9/bin/add-trailing-comma", line 8, in <module>
    sys.exit(main())
  File "/Users/paulhfischer/.cache/pre-commit/repothj9r_n4/py_env-python3.9/lib/python3.9/site-packages/add_trailing_comma.py", line 498, in main
    ret |= fix_file(filename, args)
  File "/Users/paulhfischer/.cache/pre-commit/repothj9r_n4/py_env-python3.9/lib/python3.9/site-packages/add_trailing_comma.py", line 470, in fix_file
    contents_text = _fix_src(contents_text, args.py35_plus, args.py36_plus)
  File "/Users/paulhfischer/.cache/pre-commit/repothj9r_n4/py_env-python3.9/lib/python3.9/site-packages/add_trailing_comma.py", line 401, in _fix_src
    tokens, _find_call(call, i, tokens),
  File "/Users/paulhfischer/.cache/pre-commit/repothj9r_n4/py_env-python3.9/lib/python3.9/site-packages/add_trailing_comma.py", line 239, in _find_call
    raise AssertionError('Past end?')
AssertionError: Past end?
```

**Comment by paulhfischer** [comment]
interestingly couldn't recreate it on debian … the error is caused in the file `pre_commit/languages/perl.py (added some breakpoints)

**Comment by asottile** [comment]
Neat.  Turns out this is a bug in python's new parser -- I'll see if I can work around it: https://bugs.python.org/issue42806
