### ISSUE TITLE
How to manually aply for a folder on windows?

### ISSUE THREAD

**Issue by stefaneidelloth** [asottile/add-trailing-comma#234]
I tried

`add-trailing-comma src`

and got

```
WARNING: add-trailing-comma will only use 3.6+ mode after 3.0
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\python_env\App\WinPython\python-3.11.1.amd64\Scripts\add-trailing-comma.exe\__main__.py", line 7, in <module>
  File "C:\python_env\App\WinPython\python-3.11.1.amd64\Lib\site-packages\add_trailing_comma\_main.py", line 107, in main
    ret |= fix_file(filename, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python_env\App\WinPython\python-3.11.1.amd64\Lib\site-packages\add_trailing_comma\_main.py", line 60, in fix_file
    with open(filename, 'rb') as fb:
         ^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'src'
```

**Comment by stefaneidelloth** [comment]
workaround: create *.bat file with following content and run it inside `src` folder

`for /R %%f in (*.py) do ( add-trailing-comma "%%f" )`
