### ISSUE TITLE
escaped brackets in f-string are not parsed properly for python 3.12

### ISSUE THREAD

**Issue by fayyazul-centaurlabs** [asottile/add-trailing-comma#265]
This
```python
str_1 = "{{}}"
str_2 = f"{{}}"
```
gets formatted to 
```python
str_1 = "{{}}"
str_2 = f"{}}"
```
which is no longer valid python code.

Testing further, if anything is inside the escaped brackets the tool raises an exception:
```python
str_1 = f"{{a}}"
```
raises
```python
Traceback (most recent call last):
  File "/Users/user/.cache/pre-commit/repokgbeaz2w/py_env-python3.12/bin/add-trailing-comma", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/user/.cache/pre-commit/repokgbeaz2w/py_env-python3.12/lib/python3.12/site-packages/add_trailing_comma/_main.py", line 101, in main
    ret |= fix_file(filename, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.cache/pre-commit/repokgbeaz2w/py_env-python3.12/lib/python3.12/site-packages/add_trailing_comma/_main.py", line 70, in fix_file
    contents_text = _fix_src(contents_text, args.min_version)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.cache/pre-commit/repokgbeaz2w/py_env-python3.12/lib/python3.12/site-packages/add_trailing_comma/_main.py", line 48, in _fix_src
    tokens, find_simple(i, tokens),
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.cache/pre-commit/repokgbeaz2w/py_env-python3.12/lib/python3.12/site-packages/add_trailing_comma/_token_helpers.py", line 41, in find_simple
    raise AssertionError('Past end?')
AssertionError: Past end?
```

I also tested the same examples in 3.9 and no errors were raised nor was the escaped bracket removed.

**Comment by fayyazul-centaurlabs** [comment]
nevermind, I seemed to have been using the wrong version. Sorry for the false alarm.
